services:
  server:
    build: .
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    environment:
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
      DATABASE_URL: sqlite:////app/whoskicking.db
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=8000
